org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dontRemap=true

# Minecraft / Fabric 26.3
minecraft_version=26.3
yarn_mappings=26.3+build.1
loader_version=0.19.5
loom_version=1.17.12
fabric_api_version=0.160.5+26.3

# Totem Lumen
mod_version=0.1.0-alpha.60
maven_group=dev.totem
archives_base_name=totem-lumen
