package dev.totem.lumen.render;

public enum RendererState {
    NEW,
    WAITING_FOR_DEVICE,
    DISABLED_NON_VULKAN,
    WAITING_FOR_VULKAN_INTEROP,
    DISABLED_UNSUPPORTED_VULKAN,
    WAITING_FOR_PIPELINE,
    READY_FOR_SCENE_EXTRACTION,
    PIPELINE_FAILED
}
